Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -27,7 +27,7 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install flake8 pytest
-        pip install pytest pytest-html
+        # pip install pytest pytest-html
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     - name: Lint with flake8
       run: |
@@ -37,10 +37,12 @@ jobs:
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
     - name: Test with pytest
       run: |
-        pytest -v --html=test-report.html
-    - name: Upload Test Report
-      if: always()
-      uses: actions/upload-artifact@v4
+        # pytest -v --html=test-report.html
+         python -m pytest --verbose --junit-xml=junit.xml
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
       with:
-        name: test-report+_$(date +'%Y%m%d_%H%M%S')
-        path: report.html
+         report_paths: '**/junit.xml'
+         detailed_summary: true
+         include_passed: true
